name: localization_generator
description: A window desktop application to generate localization config from excel file into .json file and LocaleKey class

version: 1.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  filesystem_picker: ^1.0.4
  filepicker_windows: ^1.0.0
  excel: ^1.1.4
  jin_widget_helper: ^2.0.1
  toast: ^0.1.5
  shared_preferences: ^0.5.12+4
  path_provider: ^1.6.25
  clipboard: ^0.1.2+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
