name: localization_generator
description: Flutter desktop application for generating JSON file and Localekeys class from Excel file or Google sheet. Using along with easy_localization package.

version: 2.2.0
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  excel: 2.0.0-null-safety-3
  sura_flutter: ^1.2.0
  sura_manager: ^1.2.1
  path_provider: ^2.0.8
  clipboard: ^0.1.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.4
  flutter_desktop_folder_picker: ^0.0.1

  toast:
    git:
      url: https://github.com/appdev/FlutterToast.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  hive_generator: ^1.1.1
  build_runner: ^2.1.5
  flutter_lints:
  flutter_launcher_icons:
    git:
      url: https://github.com/dirkbo/flutter_launcher_icons.git
      ref: master

flutter_icons:
  android: "launcher_icon"
  ios: true
  macos: true
  image_path: "assets/images/app-icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Kantumruy
      fonts:
        - asset: assets/fonts/Kantumruy-Light.ttf
        - asset: assets/fonts/Kantumruy-Regular.ttf
          weight: 500
        - asset: assets/fonts/Kantumruy-Bold.ttf
          weight: 700
